import { Input } from "@/components/ui/input";

export function EsewaForm() {
	return (
		<div>
			<form
				action="https://rc-epay.esewa.com.np/api/epay/main/v2/form"
				method="POST"
				className="flex flex-col gap-4"
			>
				<Input
					type="text"
					id="amount"
					name="amount"
					value="100"
					required
				/>
				<Input
					type="text"
					id="tax_amount"
					name="tax_amount"
					value="10"
					required
				/>
				<Input
					type="text"
					id="total_amount"
					name="total_amount"
					value="110"
					required
				/>
				<Input
					type="text"
					id="transaction_uuid"
					name="transaction_uuid"
					required
				/>
				<Input
					type="text"
					id="product_code"
					name="product_code"
					value="EPAYTEST"
					required
				/>
				<Input
					type="text"
					id="product_service_charge"
					name="product_service_charge"
					value="0"
					required
				/>
				<Input
					type="text"
					id="product_delivery_charge"
					name="product_delivery_charge"
					value="0"
					required
				/>
				<Input
					type="text"
					id="success_url"
					name="success_url"
					value="https://esewa.com.np"
					required
				/>
				<Input
					type="text"
					id="failure_url"
					name="failure_url"
					value="https://google.com"
					required
				/>
				<Input
					type="text"
					id="signed_field_names"
					name="signed_field_names"
					value="total_amount,transaction_uuid,product_code"
					required
				/>
				<Input type="text" id="signature" name="signature" required />
				<Input value="Submit" type="submit" />
			</form>
		</div>
	);
}
